### ISSUE TITLE
App suddenly crashed

### ISSUE THREAD

**Issue by safeamiiir** [mohaalak/spotify_ad_muter#1]
hey Mohammad,
first thanks for this app!
It just stopped working on my system:
OS Information: **macOS Catalina(10.15.3)**
My node version: **v13.8.0**
and another application was running on my system ( it was started by yarn)
and spotify_ad_muter was started with npm.
we have an image for more information beyond:

<img width="969" alt="Screen Shot 2020-03-02 at 8 14 10 PM" src="https://user-images.githubusercontent.com/37432754/75698023-2d809100-5cc3-11ea-9b3d-a59181fc4993.png">

**Comment by mohaalak** [comment]
oh I did not notice this issue can you confirm that this issue remains in current version

**Comment by safeamiiir** [comment]
I think its ok for now,
I just close it.
thank you
